[package]
name = "latticevm"
version = "0.0.0"
edition = "2021"
authors = ["Koukyosyumei <koukyosyumei@hotmail.com>"]
description = "Abstract-Interpretation-based Verifier for zkVM"
license = "GPL-3.0"
repository = "https://github.com/Koukyosyumei/TwinVM"
keywords = ["formal method", "security", "zero-knowledge-proof", "zkp"]

[[bin]]
name = "latticevm"
path = "src/main.rs"

[dependencies]
rand = "0.9.2"
itertools = "0.14.0"