[package]
name = "zebra_openvm"
version = "0.0.0"
edition = "2021"
authors = ["Koukyosyumei <koukyosyumei@hotmail.com>"]
description = "Abstract-Interpretation-based Verifier for OpenVM"
license = "GPL-3.0"
repository = "https://github.com/Koukyosyumei/TwinVM"
keywords = ["formal method", "security", "zero-knowledge-proof", "zkp"]

[dependencies]
rand = "0.9.2"
clap = { version = "4.5.57", features = ["derive"] }
zebra = { path = "../../" }
openvm-stark-backend = { git = "https://github.com/openvm-org/stark-backend.git", tag = "v1.1.1", default-features = false }
openvm-stark-sdk = { git = "https://github.com/openvm-org/stark-backend.git", tag = "v1.1.1", default-features = false }
openvm-circuit = { path = "../../../openvm/crates/vm", default-features = false, features = ["test-utils"] }
openvm-circuit-primitives = { path = "../../../openvm/crates/circuits/primitives", default-features = false }
openvm-circuit-primitives-derive = { path = "../../../openvm/crates/circuits/primitives/derive", default-features = false }
openvm-rv32im-circuit = { path = "../../../openvm/extensions/rv32im/circuit", default-features = false }
openvm-rv32im-transpiler = { path = "../../../openvm/extensions/rv32im/transpiler" }
openvm-instructions = { path = "../../../openvm/crates/toolchain/instructions" }

[dev-dependencies]
openvm-stark-sdk = { git = "https://github.com/openvm-org/stark-backend.git", tag = "v1.1.1", default-features = false }

[[example]]
name = "alu"

[[example]]
name = "bitwise"

[[example]]
name = "shift"

[[example]]
name = "mul"

[[example]]
name = "lt"

[[example]]
name = "branch"

[[example]]
name = "jump"
