cargo build --release --example add32
cargo build --release --example bitwise32
cargo build --release --example com32
cargo build --release --example div32
cargo build --release --example lt32
cargo build --release --example mul32
cargo build --release --example sub32
cargo build --release --example cpu
cargo build --release --example memory
