cargo build --release --example addsub
cargo build --release --example bitwise
cargo build --release --example branch
cargo build --release --example cloclz
cargo build --release --example divrem
cargo build --release --example jump
cargo build --release --example lt
cargo build --release --example memoryreadwrite
cargo build --release --example movcond
cargo build --release --example mul
cargo build --release --example shiftleft